trigger:
- master

jobs:
  - job: BuildQEMU
    pool:
      vmImage: 'Ubuntu-16.04'

    steps:
    - script: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get install android-tools-adb android-tools-fastboot autoconf automake bc bison build-essential cscope curl device-tree-compiler expect flex ftp-upload gdisk iasl libattr1-dev libc6:i386 libcap-dev libfdt-dev libftdi-dev libglib2.0-dev libhidapi-dev libncurses5-dev libpixman-1-dev libssl-dev libstdc++6:i386 libtool libz1:i386 make mtools netcat python-crypto python-serial python-wand unzip uuid-dev xdg-utils xterm xz-utils zlib1g-dev
        mkdir ../google_repo
        cd ../google_repo
        curl https://storage.googleapis.com/git-repo-downloads/repo > repo
        chmod a+x repo
        ls
      displayName: Install Tools

    - script: |
        cd ..
        mkdir qemu
        cd qemu
        export PATH=$(pwd)/../google_repo:$PATH
        repo init -u https://github.com/OP-TEE/manifest.git -m default.xml
        repo sync -j50 --no-clone-bundle
      displayName: Download QEMU

    - script: |
        cd ../qemu/build
        make -j2 toolchains
      displayName: Download QEMU Build Tools

    - script: |
        cd ../qemu/build
        make -j2
        cd ..
        ls
      displayName: Build QEMU

    - task: PublishPipelineArtifact@0
      inputs:
        artifactName: 'qemu'
        targetPath: '../qemu'

  - job: RunQEMU
    pool:
      vmImage: 'Ubuntu-16.04'
    strategy:
      matrix:
        TpmWolf:
          Target: fTPM
          Crypto: CFG_FTPM_USE_WOLF=y
        TpmOSSL:
          Target: fTPM
          Crypto: CFG_FTPM_USE_WOLF=n
        AuthvarsWolf:
          Target: AuthVars
          Crypto: CFG_AUTHVARS_USE_WOLF=y
        AuthvarsOSSL:
          Target: AuthVars
          Crypto: CFG_AUTHVARS_USE_WOLF=n

    dependsOn: BuildQEMU

    steps:
    - task: DownloadPipelineArtifact@1
      inputs:
        artifactName: 'qemu'
        downloadPath: '../qemu'

    - script: |
        cd ../qemu
        ls