trigger:
- master

jobs:
  - job: BuildTA32
    pool:
      vmImage: 'Ubuntu-16.04'

    steps:
    - script: |
        cd ..
        git clone https://github.com/ms-iot/optee_os.git
      displayName: Clone OP-TEE